services:
  # ===============================
  #  ZOOKEEPER
  # ===============================
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  # ===============================
  #  KAFKA
  # ===============================
  kafka:
    image: confluentinc/cp-kafka:7.3.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"   # container-to-container (Spark)
      - "29092:29092" # host access
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  # ===============================
  #  REDIS
  # ===============================
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  # ===============================
  #  PRODUCER
  # ===============================
  producer:
    build: ./producer
    container_name: producer
    depends_on:
      - kafka
    volumes:
      - ./data:/data
    environment:
      - KAFKA_BOOTSTRAP=kafka:9092
    restart: unless-stopped

  # ===============================
  #  SPARK STREAMING
  # ===============================
  spark:
    build: ./spark
    container_name: spark
    depends_on:
      - kafka
      - redis
    environment:
      - PYSPARK_PYTHON=python3
    volumes:
      - ./spark/app:/app
    restart: unless-stopped

  # ===============================
  #  WEBUI (Flask + frontend)
  # ===============================
  webui:
    build: ./webui
    container_name: webui
    depends_on:
      - redis
    ports:
      - "5000:5000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_KEY=live_metrics
    restart: unless-stopped
